pipeline {
	agent any
    tools{
			maven 'myMaven-3'
			jdk 'myJDK-1.8'
		 } 
	stages{
		stage('Build Selected branshes') {
            when { branch 'dev*' }
            steps {
                sh 'echo "Build for $BRANCH_NAME"'
            }
        }
        stage('Push selected branches to Artifactory') {
            when { branch 'dev*' }
            steps {
                sh 'echo "Artifactory for $BRANCH_NAME"'
            }
        }
	   stage('Process the rest') {
            when { branch 'master' }
            steps {
                sh 'echo "Build another branch $BRANCH_NAME"'
            }
        }
    }
}